# Site settings
title: Michael Ayvazyan
description: 'Software Development in a Nutshell'
url: 'http://ayvazyan.net'
baseurl: ''
google_analytics: 'UA-74010101-1'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Michael Ayvazyan'
  github_username:  mayvazyan
  linkedin_username:  michaelayvazyan

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
excerpt_separator: <!--more-->
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
